#pragma once
enum class Commands { HELLO, CHALLENGE, CHALLENGE_RESPONSE, WELCOME, NEW_PLAYER, ACKNOWLEDGE_WELCOME, START, ACKNOWLEDGE_START, READY, NEW_POSITION, UPDATE_POSITION, VALIDATE_POSITION, NEW_BULLET, ACKNOWLEDGE_BULLET, NEW_REMOTE_BULLET, ACKNOWLEDGE_REMOTE_BULLET, PLAY_AGAIN, PLAY_AGAIN_ANSWER, NEW_GAME, ACKNOWLEDGE_NEW_GAME, PLAYER_DISCONNECTED, BYE_SERVER, BYE_CLIENT, ACKNOWLEDGE_BYE_SERVER, ACKNOWLEDGE_BYE_CLIENT};
const int WAIT_FOR_CONNECTION_TIME = 2; //in seconds
const int WAIT_FOR_PLAY_AGAIN_TIME = 7; //in seconds
const int WAIT_FOR_BULLET_RESPONSE_TIME = 2; //in seconds
const int WAIT_BEFORE_DESCONNECTING_TIME = 30; //in seconds
const int START_SEND_RATE = 2000; //in milliseconds
const int POSITION_SEND_RATE = 50; //in milliseconds
const int BULLET_SHOOT_RATE = 200; //in milliseconds
const int BULLET_SEND_RATE = 20; //in milliseconds
const int BULLET_ERASE_REF = 1;//in seconds
const int MAX_TIME_PLAYING = 30; //in seconds
const int MAX_PLAYERS_IN_A_ROOM = 2;
const int LOST_PACKETS_PERCENTAGE = 5;
const float BLOCK_SIZE = 20.f;
const int W_WINDOW_PX = 800;
const int H_WINDOW_PX = 600;
const int SERVER_PORT = 51000;